name: Publish Extension

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run package
    - name: Release
      uses: softprops/action-gh-release@v2
      with:
          generate_release_notes: true
          files: usedhondacivic.teleop-twist-keyboard-${{ github.ref_name }}.foxe
